namespace Maple.Core.Skills;

/// <summary>玩家 buff bit index，數值對齊 Java MapleBuffStat 建構子參數。</summary>
public enum MapleBuffStat
{
    WATK = 0,
    WDEF = 1,
    MATK = 2,
    MDEF = 3,
    ACC = 4,
    AVOID = 5,
    HANDS = 6,
    SPEED = 7,
    JUMP = 8,
    MAGIC_GUARD = 9,
    DARKSIGHT = 10,
    BOOSTER = 11,
    POWERGUARD = 12,
    MAXHP = 13,
    MAXMP = 14,
    INVINCIBLE = 15,
    SOULARROW = 16,
    STUN = 17,
    POISON = 18,
    SEAL = 19,
    DARKNESS = 20,
    COMBO = 21,
    SUMMON = 21,
    WK_CHARGE = 22,
    DRAGONBLOOD = 23,
    HOLY_SYMBOL = 24,
    MESOUP = 25,
    SHADOWPARTNER = 26,
    PICKPOCKET = 27,
    PUPPET = 28,
    MESOGUARD = 29,
    HP_LOSS_GUARD = 30,
    WEAKEN = 30,
    CURSE = 31,
    SLOW = 32,
    MORPH = 33,
    RECOVERY = 34,
    MAPLE_WARRIOR = 35,
    STANCE = 36,
    SHARP_EYES = 37,
    MANA_REFLECTION = 38,
    DRAGON_ROAR = 39,
    SPIRIT_CLAW = 40,
    INFINITY = 41,
    HOLY_SHIELD = 42,
    HAMSTRING = 43,
    BLIND = 44,
    CONCENTRATE = 45,
    ZOMBIFY = 46,
    ECHO_OF_HERO = 47,
    UNKNOWN3 = 48,
    GHOST_MORPH = 49,
    ARIANT_COSS_IMU = 50,
    DROP_RATE = 52,
    MESO_RATE = 53,
    EXPRATE = 54,
    ACASH_RATE = 55,
    GM_HIDE = 56,
    BERSERK_FURY = 57,
    ILLUSION = 58,
    SPARK = 59,
    DIVINE_BODY = 60,
    FINAL_MELEE_ATTACK = 61,
    FINAL_SHOOT_ATTACK = 62,
    ELEMENT_RESET = 63,
    WIND_WALK = 64,
    UNKNOWN7 = 65,
    ARAN_COMBO = 66,
    COMBO_DRAIN = 67,
    COMBO_BARRIER = 68,
    BODY_PRESSURE = 69,
    SMART_KNOCKBACK = 70,
    SOUL_STONE = 73,
    ENERGY_CHARGE = 75,
    DASH_SPEED = 76,
    DASH_JUMP = 77,
    MONSTER_RIDING = 78,
    SPEED_INFUSION = 79,
    HOMING_BEACON = 80,
    SOARING = 82,
    FREEZE = 83,
    LIGHTNING_CHARGE = 84,
    MIRROR_IMAGE = 85,
    OWL_SPIRIT = 86,
}

public static class MapleBuffStatExtensions
{
    public static int GetMaskPosition(this MapleBuffStat stat)
        => 3 - ((int)stat / 32);

    public static int GetMaskValue(this MapleBuffStat stat)
        => unchecked((int)(1u << ((int)stat % 32)));
}
