<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Maple.Core\Maple.Core.csproj" />
    <ProjectReference Include="..\Maple.Versioning\Maple.Versioning.csproj" />
    <ProjectReference Include="..\Maple.Net\Maple.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Maple.Adapters.V113.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
