namespace Maple.Adapters.V113.Channel;

/// <summary>v113 Channel 接收 opcode。</summary>
internal static class V113ChannelRecvOp
{
    public const short PlayerLoggedIn = 0x07;
    public const short ChangeMap = 0x1E;     // 腳走地圖傳送點 / 死亡復活換圖（CHANGE_MAP）
    public const short ChangeChannel = 0x1F;
    public const short MovePlayer = 0x21;
    public const short CancelChair = 0x22;
    public const short UseChair = 0x23;
    public const short CloseRangeAttack = 0x25;
    public const short RangedAttack = 0x26;
    public const short MagicAttack = 0x27;
    public const short TakeDamage = 0x29;
    public const short GeneralChat = 0x2A;   // 一般地圖聊天
    public const short CloseChalkboard = 0x2B;
    public const short FaceExpression = 0x2C;
    public const short UseItemEffect = 0x2D;
    public const short MonsterBookCover = 0x32;
    public const short DueyAction = 0x3B;
    public const short Owl = 0x3C;
    public const short OwlWarp = 0x3D;
    public const short SpecialMove = 0x55;
    public const short CancelBuff = 0x56;
    public const short SkillEffect = 0x57;
    public const short MesoDrop = 0x58;
    public const short GiveFame = 0x59;
    public const short CharInfoRequest = 0x5B;
    public const short UseInnerPortal = 0x5F;
    public const short TrockAddMap = 0x60;
    public const short SkillMacro = 0x68;
    public const short DistributeAp = 0x51;
    public const short HealOverTime = 0x53;
    public const short DistributeSp = 0x54;
    public const short QuestAction = 0x65;
    public const short PartyChat = 0x70;
    public const short Whisper = 0x71;
    public const short PartyOperation = 0x74;
    public const short GuildOperation = 0x76;
    public const short DenyGuildRequest = 0x77;
    public const short BuddyListModify = 0x7A;
    public const short ChangeKeymap = 0x7F;
    public const short UpdateCharInfo = 0x97;
    public const short UpdateQuest = 0x10B;
    public const short UseItemQuest = 0x10D;
    public const short NpcTalk = 0x33;       // 點 NPC → 啟動對話腳本
    public const short NpcTalkMore = 0x35;   // 對話中回應（next/prev/yes-no/選單/數字）
    public const short NpcShop = 0x36;
    public const short Storage = 0x37;
    public const short ItemSort = 0x3F;
    public const short ItemGather = 0x40;
    public const short ItemMove = 0x41;      // 背包格內移動 / 穿脫裝 / 丟棄（dst=0）
    public const short UseItem = 0x42;
    public const short CancelItemEffect = 0x43;
    public const short UseSummonBag = 0x45;
    public const short UseMountFood = 0x47;
    public const short UseCashItem = 0x49;
    public const short UseCatchItem = 0x4B;
    public const short UseReturnScroll = 0x4F;
    public const short UseUpgradeScroll = 0x50;
    public const short UseSkillBook = 0x4C;
    public const short UseOwlMinerva = 0x4D;
    public const short PlayerInteraction = 0x73;
    public const short ItemPickup = unchecked((short)0xC6);
    public const short RingAction = unchecked((short)0x81);
    public const short BbsOperation = unchecked((short)0x94);
    public const short Solomon = unchecked((short)0x9B);
    public const short GachExp = unchecked((short)0x9C);
    public const short TransformPlayer = unchecked((short)0xA0);
    public const short XmasSurprise = unchecked((short)0xA2);
    public const short MoveLife = unchecked((short)0xB6);       // 怪物移動（MOVE_LIFE）
    public const short AutoAggro = unchecked((short)0xB7);     // 怪物自動仇恨（AUTO_AGGRO）
    public const short DamageReactor = unchecked((short)0xC9);
    public const short TouchReactor = unchecked((short)0xCA);
    public const short PetFood = 0x46;
    public const short SpawnPet = 0x5C;
    public const short MovePet = unchecked((short)0xA4);
    public const short PetChat = unchecked((short)0xA5);
    public const short PetCommand = unchecked((short)0xA6);
    public const short PetLoot = unchecked((short)0xA7);
    public const short PetAutoPot = unchecked((short)0xA8);
    public const short PetIgnore = unchecked((short)0xA9);
    public const short MoveSummon = unchecked((short)0xAC);
    public const short SummonAttack = unchecked((short)0xAD);
    public const short DamageSummon = unchecked((short)0xAE);
    public const short SubSummon = unchecked((short)0xAF);
    public const short NpcAction = unchecked((short)0xBF);
    public const short AutoAssignAp = 0x52;
    public const short CancelDebuff = 0x5D;
    public const short ChangeMapSpecial = 0x5E;
    public const short Messenger = 0x72;
    public const short DenyPartyRequest = 0x75;
    public const short NoteAction = 0x7B;
    public const short UseDoor = 0x7D;
    public const short AllianceOperation = unchecked((short)0x86);
    public const short DenyAllianceRequest = unchecked((short)0x87);
    public const short RequestFamily = unchecked((short)0x88);
    public const short OpenFamily = unchecked((short)0x89);
    public const short FamilyOperation = unchecked((short)0x8A);
    public const short DeleteJunior = unchecked((short)0x8B);
    public const short DeleteSenior = unchecked((short)0x8C);
    public const short AcceptFamily = unchecked((short)0x8D);
    public const short UseFamily = unchecked((short)0x8E);
    public const short FamilyPrecept = unchecked((short)0x8F);
    public const short FamilySummon = unchecked((short)0x90);
    public const short PartySearchStart = unchecked((short)0xD9);
    public const short PartySearchStop = unchecked((short)0xDA);
    public const short CashShopOperation = unchecked((short)0xE6);
    public const short Pong = 0x0E;
}

/// <summary>v113 Channel 送出 opcode。</summary>
internal static class V113ChannelSendOp
{
    public const short SetField = 0x7B;   // WARP_TO_MAP / initial login / map change
    public const short ChangeChannel = 0x08;
    public const short ChatText = unchecked((short)0x9B);   // 地圖聊天泡泡
    public const short ShowScrollEffect = unchecked((short)0x9F);
    public const short Ping = 0x09;
    public const short ModifyInventoryItem = 0x1B;   // 背包變更（新增/數量/移動/移除）
    public const short UpdateStats = 0x1D;
    public const short GiveBuff = 0x1E;
    public const short CancelBuff = 0x1F;
    public const short UpdateSkills = 0x22;
    public const short SkillUseResult = 0x23;
    public const short FameResponse = 0x24;
    public const short ShowStatusInfo = 0x25;
    public const short MapTransferResult = 0x27;
    public const short ShowQuestCompletion = 0x2E;
    public const short GatherItemResult = 0x32;
    public const short SortItemResult = 0x33;
    public const short CharInfo = 0x36;
    public const short PartyOperation = 0x37;
    public const short BuddyList = 0x38;
    public const short GuildOperation = 0x3A;
    public const short ShopScannerResult = 0x3F;
    public const short ShopLinkResult = 0x40;
    public const short MarriageRequest = 0x41;
    public const short MarriageResult = 0x42;
    public const short MonsterBookChangeCover = 0x4E;
    public const short MarriageUpdate = 0x62;
    public const short BbsOperation = 0x68;
    public const short SkillMacro = 0x7A;
    public const short MultiChat = 0x84;
    public const short Whisper = 0x85;
    public const short SpawnNpc = unchecked((short)0xF9);              // SPAWN_NPC
    public const short RemoveNpc = unchecked((short)0xFA);            // REMOVE_NPC
    public const short SpawnNpcRequestController = unchecked((short)0xFB);  // SPAWN_NPC_REQUEST_CONTROLLER
    public const short CloseRangeAttack = unchecked((short)0xB2);
    public const short RangedAttack = unchecked((short)0xB3);
    public const short MagicAttack = unchecked((short)0xB4);
    public const short SkillEffect = unchecked((short)0xB6);
    public const short CancelSkillEffect = unchecked((short)0xB7);
    public const short DamagePlayer = unchecked((short)0xB8);
    public const short FacialExpression = unchecked((short)0xB9);
    public const short ShowItemEffect = unchecked((short)0xBA);
    public const short ShowChair = unchecked((short)0xBD);
    public const short ShowForeignEffect = unchecked((short)0xBF);
    public const short Chalkboard = unchecked((short)0x9C);
    public const short GiveForeignBuff = unchecked((short)0xC0);
    public const short CancelForeignBuff = unchecked((short)0xC1);
    public const short RepairWindow = unchecked((short)0xD5);
    public const short NpcTalk = 0x13C;   // NPC 對話框（getNPCTalk，2-byte opcode）
    public const short OpenNpcShop = 0x13D;
    public const short ConfirmShopTransaction = 0x13E;
    public const short OpenStorage = 0x141;
    public const short PlayerInteraction = 0x146;
    public const short CashShopUpdate = 0x157;
    public const short CashShopOperation = 0x158;
    public const short Duey = 0x155;
    public const short XmasSurprise = 0x161;
    public const short Keymap = 0x163;
    public const short SpawnMonster = unchecked((short)0xE5);
    public const short KillMonster = unchecked((short)0xE6);
    public const short SpawnMonsterControl = unchecked((short)0xE7);
    public const short MoveMonster = unchecked((short)0xE8);
    public const short MoveMonsterResponse = unchecked((short)0xE9);
    public const short DamageMonster = unchecked((short)0xEF);
    public const short ShowItemGainInChat = unchecked((short)0xC7);
    public const short DropItemFromMapObject = 0x107;
    public const short RemoveItemFromMap = 0x108;
    public const short ReactorHit = 0x113;
    public const short ReactorSpawn = 0x115;
    public const short ReactorDestroy = 0x116;
    public const short UpdatePartyMemberHp = unchecked((short)0xC2);
    public const short CancelChair = unchecked((short)0xC6);
    public const short CurrentMapWarp = unchecked((short)0xC8);
    public const short UpdateQuestInfo = unchecked((short)0xCC);
    public const short UseSkillBook = 0x31;
    public const short NpcAction = unchecked((short)0xFC);

    public const short ShowNotes = 0x26;
    public const short SendAllianceOperation = 0x3B;
    public const short FamilyChartResult = 0x56;
    public const short FamilyInfoResult = 0x57;
    public const short FamilyResult = 0x58;
    public const short FamilyJoinRequest = 0x59;
    public const short FamilyJunior = 0x5A;
    public const short FamilyJoinAccepted = 0x5B;
    public const short FamilyPrivilegeList = 0x5C;
    public const short FamilyFamousPointIncResult = 0x5D;
    public const short FamilyNotifyLoginOrLogout = 0x5E;
    public const short FamilySetPrivilege = 0x5F;
    public const short FamilySummonRequestSend = 0x60;
    public const short SendMessenger = 0x145;
}
